Config = {}
Config.Lang = "Italian" -- "English" or "Italian"

Config.OpenWithCommand = false
Config.OpenCommand = "skill"

Config.OpenWithKey = true
Config.OpenButton  = 0x446258B6 -- [PAGEUP]

Config.DiscordAvatar = false
Config.guildId = ""
Config.DiscordToken = ""

Config.EXP = {
    IncreaseTime    = 180000, -- 3 mins
    IncrementPoints = 2.5
}

Config.Perks = {
    {
        icon  = "ability_card_slippery_bastard",
        label = "Slippery bastard",
        desc  = "Increase your inventory capacity by double",
        funcs = "slippery_bastard",
        point = 110,
        money = 850
    },
    {
        icon  = "ability_card_a_moment_to_recuperate",
        label = "A moment to recuperate",
        desc  = "Slowly regenerates stress in relaxation zones",
        funcs = "a_moment_to_recuperate",
        point = 90,
        money = 625
    },
    {
        icon  = "ability_card_quite_an_inspiration",
        label = "Quite an inspiration",
        desc  = "Every 10 minutes, adds double EXP to the character.",
        funcs = "quite_an_inspiration",
        point = 70,
        money = 450
    },
    {
        icon  = "ability_card_sharpshooter",
        label = "Sharpshooter",
        desc  = "Gain Gunslinger experience 3x faster",
        funcs = "sharpshooter",
        point = 160,
        money = 1400
    },
    {
        icon  = "ability_card_strange_medicine",
        label = "Strange medicine",
        desc  = "When you respawn there will be a 50% chance of not getting sick",
        funcs = "strange_medicine",
        point = 130,
        money = 1185
    },
    {
        icon  = "ability_card_the_unblinking_eye",
        label = "The unblinking eye",
        desc  = "Regenerates health and stamina at double the rate",
        funcs = "the_unblinking_eye",
        point = 180,
        money = 1750
    },
    {
        icon  = "ability_card_gunslingers_choice",
        label = "Gunslingers_choice",
        desc  = "When you hold a weapon or shoot you will no longer experience stress.",
        funcs = "gunslingers_choice",
        point = 150,
        money = 1250
    },
    {
        icon  = "ability_card_take_the_pain_away",
        label = "Take the pain away",
        desc  = "Restore health and stamina by taking a luxurious bath",
        funcs = "take_the_pain_away",
        point = 120,
        money = 975
    }
}

Config.Skills = {
    {
        skillName  = "Weapons",
        skillLabel = "Gunslinger",
        {
            liv = 1,
            label = "Novice",
            rewardType = "weapon",
            rewardName = "WEAPON_REVOLVER_CATTLEMAN",
            RewardLabel = "Revolver Cattleman",
            amount = "1",
        },
        {
            liv = 2,
            label = "Test 2",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 3,
            label = "Test 3",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 4,
            label = "Test 4",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 5,
            label = "Test 5",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 6,
            label = "Test 6",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 7,
            label = "Test 7",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 8,
            label = "Test 8",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 9,
            label = "Test 9",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 10,
            label = "Test 10",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
    },
    {
        skillName  = "Mining",
        skillLabel = "Miner",
        {
            liv = 1,
            label = "Test 1",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Coal",
            amount = "5",
        },
        {
            liv = 2,
            label = "Test 2",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 3,
            label = "Test 3",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 4,
            label = "Test 4",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 5,
            label = "Test 5",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 6,
            label = "Test 6",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 7,
            label = "Test 7",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 8,
            label = "Test 8",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 9,
            label = "Test 9",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 10,
            label = "Test 10",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
    },
    -- {
    --     skillName  = "Blacksmith",
    --     skillLabel = "Fabbro",
    -- },
    {
        skillName  = "Naturalist",
        skillLabel = "Naturalist",
        {
            liv = 1,
            label = "Colt Navy",
            rewardType = "weapon",
            rewardName = "WEAPON_REVOLVER_NAVY",
            RewardLabel = "Colt Navy",
            amount = "1",
        },
        {
            liv = 2,
            label = "Test 2",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 3,
            label = "Test 3",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 4,
            label = "Test 4",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 5,
            label = "Test 5",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 6,
            label = "Test 6",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 7,
            label = "Test 7",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 8,
            label = "Test 8",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 9,
            label = "Test 9",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 10,
            label = "Test 10",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
    },
    {
        skillName  = "Fishing",
        skillLabel = "Fisherman",
        {
            liv = 1,
            label = "Novizio",
            rewardType = "weapon",
            rewardName = "WEAPON_FISHINGROD",
            RewardLabel = "Canna da Pesca",
            amount = "1",
        },
        {
            liv = 2,
            label = "Test 2",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 3,
            label = "Test 3",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 4,
            label = "Test 4",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 5,
            label = "Test 5",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 6,
            label = "Test 6",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 7,
            label = "Test 7",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 8,
            label = "Test 8",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 9,
            label = "Test 9",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 10,
            label = "Test 10",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
    },
    {
        skillName  = "Doctor",
        skillLabel = "Doctor",
        {
            liv = 1,
            label = "Colt Navy",
            rewardType = "weapon",
            rewardName = "WEAPON_REVOLVER_NAVY",
            RewardLabel = "Colt Navy",
            amount = "1",
        },
        {
            liv = 2,
            label = "Test 2",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 3,
            label = "Test 3",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 4,
            label = "Test 4",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 5,
            label = "Test 5",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 6,
            label = "Test 6",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 7,
            label = "Test 7",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 8,
            label = "Test 8",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 9,
            label = "Test 9",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 10,
            label = "Test 10",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
    },
    -- {
    --     skillName  = "Nativo",
    --     skillLabel = "Indiano",
    -- },
    {
        skillName  = "Hunting",
        skillLabel = "Hunter",
        {
            liv = 1,
            label = "Test 1",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 2,
            label = "Test 2",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 3,
            label = "Test 3",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 4,
            label = "Test 4",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 5,
            label = "Test 5",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 6,
            label = "Test 6",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 7,
            label = "Test 7",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 8,
            label = "Test 8",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 9,
            label = "Test 9",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
        {
            liv = 10,
            label = "Test 10",
            rewardType = "item",
            rewardName = "coal",
            RewardLabel = "Carbone",
            amount = "1",
        },
    }
}